name: Test iOS build on Fabric
on:
  pull_request:
    branches:
      - main
      - main-labs
    paths:
      - '.github/workflows/ios-build-test-fabric.yml'
      - 'RNScreens.podspec'
      - 'package.json'
      - 'ios/**'
      - 'common/**'
      - 'src/fabric/**'
      - 'FabricExample/**'
  push:
    branches:
      - main
      - main-labs
  workflow_dispatch:
jobs:
  build:
    runs-on: macos-26-xlarge
    timeout-minutes: 60
    env:
      WORKING_DIRECTORY: FabricExample
      RNS_GAMMA_ENABLED: 1
    concurrency:
      group: ios-fabric-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Setup Node.js (version from .nvmrc)
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'
          cache-dependency-path: ${{ env.WORKING_DIRECTORY }}/yarn.lock
      - name: Use latest stable Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '26.2'
      - name: Install node dependencies
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: yarn

        # This step is required due to the bug introduced in 1.15.0 version of cocoapods
        # that breaks the pod installation for cached packages.
        # see https://github.com/facebook/react-native/issues/42698
        # This step should be removed once this issue will be resolved:
        # https://github.com/actions/runner-images/issues/9308
      - name: Install Ruby gems
        run: gem install cocoapods -v 1.15.2

      - name: Install pods
        id: install_pods
        continue-on-error: true
        working-directory: ${{ env.WORKING_DIRECTORY }}/ios
        run: pod install

      - if: steps.install_pods.outcome == 'failure'
        id: remove_pods
        name: Remove pods
        working-directory: ${{ env.WORKING_DIRECTORY }}/ios
        run: rm -fr build Pods Podfile.lock

      - if: steps.remove_pods.outcome == 'success'
        id: reinstall_pods
        name: Reinstall pods
        working-directory: ${{ env.WORKING_DIRECTORY }}/ios
        run: pod install

      - name: Build app
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: npx react-native run-ios --no-packager --simulator="iPhone 17"
