name: Test iOS e2e - new architecture
on:
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/ios-e2e-test-fabric.yml'
      - 'RNScreens.podspec'
      - 'package.json'
      - 'ios/**'
      - 'common/**'
      - 'FabricExample/**'
      - 'src/**'
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  test:
    runs-on: macos-26-xlarge
    timeout-minutes: 90
    env:
      WORKING_DIRECTORY: FabricExample
    concurrency:
      group: ios-e2e-fabric-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Setup Node.js (version from .nvmrc)
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'
      - name: Use latest stable Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '26.2'
      - name: Get Xcode version
        run: xcodebuild -version
      - name: Install AppleSimulatorUtils
        run: brew tap wix/brew && brew install applesimutils
      - name: Install root node dependencies
        run: yarn install && yarn submodules
      - name: Install node dependencies
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: yarn
        # This step is required due to the bug introduced in 1.15.0 version of cocoapods
        # that breaks the pod installation for cached packages.
        # see https://github.com/facebook/react-native/issues/42698
        # This step should be removed once this issue will be resolved:
        # https://github.com/actions/runner-images/issues/9308
      - name: Install Ruby gems
        run: gem install cocoapods -v 1.15.2
      - name: Install pods
        working-directory: ${{ env.WORKING_DIRECTORY }}/ios
        run: pod install
      - name: Build app
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: yarn build-e2e-ios
      - name: Test app
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: yarn test-e2e-ios
      - uses: actions/upload-artifact@v4
        if: ${{ failure() }}
        with:
          name: ios-fail-screen-shots
          path: ${{ env.WORKING_DIRECTORY }}/artifacts
