name: Test iOS build on Fabric
on:
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/ios-build-test-fabric.yml'
      - 'RNScreens.podspec'
      - 'package.json'
      - 'ios/**'
      - 'common/**'
      - 'src/fabric/**'
      - 'FabricTestExample/**'
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    runs-on: macos-12
    timeout-minutes: 60
    env:
      WORKING_DIRECTORY: FabricTestExample
    concurrency:
      group: ios-fabric-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Use Node.js 18
        uses: actions/setup-node@v2
        with:
          node-version: 18
          cache: 'yarn'
          cache-dependency-path: 'FabricTestExample/yarn.lock'

      - name: Install node dependencies
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: yarn

      - name: Install pods
        id: install_pods
        continue-on-error: true
        working-directory: ${{ env.WORKING_DIRECTORY }}/ios
        run: RCT_NEW_ARCH_ENABLED=1 pod install

      - if: steps.install_pods.outcome == 'failure'
        id: remove_pods
        name: Remove pods
        working-directory: ${{ env.WORKING_DIRECTORY }}/ios
        run: rm -fr build Pods Podfile.lock

      - if: steps.remove_pods.outcome == 'success'
        id: reinstall_pods
        name: Reinstall pods
        working-directory: ${{ env.WORKING_DIRECTORY }}/ios
        run: RCT_NEW_ARCH_ENABLED=1 pod install

      - name: Build app
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: yarn ios
